config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :shipper_login, :transporter_login, :nominations
    
    root "shipper_login#index"
     
    get "/shipper", to: "shipper_login#index"
    get "/transporter", to: "transporter_login#index"
   get "/nominations/schedule", to: "nominations#show" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login
     
end

app/models/nomination.rb
class Nomination <  ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
 #  include ActiveModel::Validations
    def index
    end
end

app/controllers/nominations_controller.rb
require 'net/http'
require 'uri'
require 'json'
class NominationsController < ApplicationController
       
    def index
        if($userRole_frm == "Supplier")
            @user_id = $user_id_supplier
        elsif($userRole_frm == "Transporter")
            @user_id = $user_id_transporter 
        end
      
        uri = URI('http://gas-poc4.cfapps.io/GAS/services/viewnomination/')
        http = Net::HTTP.new(uri.host, uri.port)
        req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
        req.body = {"userid" => @user_id}.to_json
        res = http.request(req)
        hash_response  = JSON.parse(res.body)
        @nominations = hash_response         
        respond_to do |format|
          format.html  
         format.json  { render :json => @nominations }
        end
    end
    
   def new
        @nomination = ""
        @status = params[:status]
        @capacityRef = params[:capacity_ref]
        @fname = params[:fname]
        @startdate_and_time = params[:startdate_and_time]
        @enddate_and_time = params[:enddate_and_time]
        @injection_point = params[:injection_point]
        @injection_quantity = params[:injection_quantity]
        @offtake_point = params[:offtake_point]
        @offtake_quantity = params[:offtake_quantity]
        @nomination_type = params[:nomination_type]
        @statusNomination = params[:statusNomination]
        @nominationid = params[:nominationid]

   end
    
                                 
    def show
        @window = params[:id]
        if(@window == "notification")
            json_response  = File.read("#{Rails.root}/mockJsonNotify.json")
            hash_response  = JSON.parse(json_response )
            @notifications = hash_response         
            respond_to do |format|
               format.html  {render "nominations/notification"}
               format.json  { render :json => @notifications }
            end
        elsif(@window == "schedule")
             begin
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/viewscheduler/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = { "userid" => "All"}.to_json 
                res = http.request(req)
                hash_response  = JSON.parse(res.body)
                @schedules = hash_response   
                respond_to do |format|
                    format.html  {render "nominations/schedule"}
                    format.json  { render :json => @schedules }
                end
            end
        end
     end
    
    def create
        if params[:hiddenStatus] == "Create"
            begin
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/addnomination/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = { "startdate_and_time" => params[:nominationstartdate],
                            "enddate_and_time" => params[:nominationenddate],
                            "injection_point" => params[:injectionpoint],
                            "injection_quantity" => params[:injectionquantity].to_i,
                            "offtake_point" => params[:offtakepoint],
                            "offtake_quantity" => params[:offtakequantity].to_i,
                            "capacity_ref" => params[:capacity],
                            "status" => "Accepted",
                            "uid" => ($user_id_supplier.to_i)}.to_json 
                res = http.request(req)
                data_hash = JSON.parse(res.body)
                redirect_to :controller => "nominations", :action => "index"  
            end
        elsif params[:hiddenStatus] == "Modify"
            begin
                uri = URI('http://gas-poc4.cfapps.io/GAS/services/modifynomination/')
                http = Net::HTTP.new(uri.host, uri.port)
                req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
                req.body = {"nominationid" =>params[:hiddenNominationId].to_i,
                            "startdate_and_time" => params[:nominationstartdate],
                            "enddate_and_time" => params[:nominationenddate],
                            "injection_point" => params[:injectionpoint],
                            "injection_quantity" => params[:injectionquantity].to_i,
                            "offtake_point" => params[:offtakepoint],
                            "offtake_quantity" => params[:offtakequantity].to_i,
                            "capacity_ref" => params[:capacity]}.to_json 
                res = http.request(req)
                data_hash = JSON.parse(res.body)
                redirect_to :controller => "nominations", :action => "index"  
            end
           
        end
        
    end       
end

app/controllers/shipper_login_controller.rb
require 'net/http'
require 'uri'
require 'json'
class ShipperLoginController < ApplicationController
    def index
        @slogin = ""
    end     
    
    def create
        @userId = params[:username]
        @pwd = params[:password]
        $userRole_frm = params[:hiddenType]
        @error = ""
        begin
            uri = URI('http://gas-poc4.cfapps.io/GAS/services/login/')
            http = Net::HTTP.new(uri.host, uri.port)
            req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
            req.body = {"user_name" => @userId, "pwd" => @pwd,"user_role" => $userRole_frm}.to_json
            res = http.request(req)
            data_hash = JSON.parse(res.body)
            $user_id_supplier = data_hash["userid"].to_s
                   
           if data_hash["status"] == "Success"
                redirect_to :controller => "nominations", :action => "index"  
           end
        end
    end
end

app/controllers/transporter_login_controller.rb
require 'net/http'
require 'uri'
require 'json'
class TransporterLoginController < ApplicationController
    def index
        @tlogin = ""
    end     
    
    def create
        @userId = params[:username]
        @pwd = params[:password]
        $userRole_frm = params[:hiddenType]
         begin
            uri = URI('http://gas-poc4.cfapps.io/GAS/services/login/')
            http = Net::HTTP.new(uri.host, uri.port)
            req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
            req.body = {"user_name" => @userId, "pwd" => @pwd,"user_role" => $userRole_frm}.to_json
            res = http.request(req)
            data_hash = JSON.parse(res.body)
            puts data_hash["status"]
            $user_id_transporter = "All"
           if data_hash["status"] == "Success"
                redirect_to :controller => "nominations", :action => "index"   
           end
            
            
        end        
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
    #check the url and append active class to it
    def is_active?(link_path)
     current_page?(link_path) ? "active" : ""
    end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/helpers/shipper_login_helper.rb
module ShipperLoginHelper
end

app/helpers/transporter_login_helper.rb
module TransporterLoginHelper
end

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-inverse top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         <%= image_tag("logo.png", size: "144X19", class: "img-fluid logo") %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= image_tag("profile_photo.png", size: "37X38", class: "img-fluid profile") %>Hi Smith</a>
            <div class="dropdown-menu" aria-labelledby="dropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
            <li><%= image_tag("setting_icon.png", size: "24X24", class: "img-fluid icons") %></li>
            <li><%= image_tag("report_issue.png", size: "24X24", class: "img-fluid icons") %></li>
            <li><%= image_tag("help.png", size: "24X24", class: "img-fluid icons") %></li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_sidenav.html.erb
 <div id="navbar" class="navbar-collapse collapse">
  <ul class="nav sidebar-nav">              
    <li>
        <a href="#" class="btn">
            <span class="glyphicon"><%= image_tag("home.png", size: "24X24", class: "img-fluid icons") %></span>Home
        </a>
    </li>
    <li class="<%= is_active?('/nominations') %> <%= is_active?('/nominations/new') %>">
        <%= link_to '/nominations', class:"btn"  do %>
        <span class="glyphicon"><%= image_tag("nomination_icon.png", size: "24X24", class: "img-fluid icons") %></span>Nominations
        <% end %>
    </li>
    <li class="<%= is_active?('/nominations/schedule') %>">
        <%= link_to '/nominations/schedule', class:"btn" do %>
        <span class="glyphicon"><%= image_tag("scheduling.png", size: "24X24", class: "img-fluid icons") %></span>scheduling
        <% end %>
    </li>
    <li>
        <a href="#" class="btn">
            <span class="glyphicon"><%= image_tag("consumption_icon.png", size: "24X24", class: "img-fluid icons") %></span>Consumption
        </a>
    </li>
    <li>
        <a href="#" class="btn">
            <span class="glyphicon"><%= image_tag("billing.png", size: "24X24", class: "img-fluid icons") %></span>Billing
        </a>
    </li>
    <li class="<%= is_active?('/nominations/notification') %>">
        <%= link_to '/nominations/notification', class: "btn" do %>
        <span class="glyphicon"><%= image_tag("notification.png", size: "24X24", class: "img-fluid icons") %></span>Notifications
        <% end%>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GasnetPoc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container-fluid">
    <%= yield %>
          </div>
  </body>
</html>

app/views/login/index.html.erb
<h6> Working...</h6>

app/views/nominations/index.html.erb
<%= render "layouts/header"  %>

<div class="container-fluid white-container nopad">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <%= render "layouts/sidenav"  %>       
        </div>
        <div class="col-sm-9 col-md-11">        
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
        <div class="pull-left"> <h3 class="pageheading">All Nominations</h3></div>
        <% if ($userRole_frm == "Supplier")  %>
            <div class="pull-right">
                <%= link_to "<button class='btn btn-primary btn-small'>Create Nomination</button>".html_safe, new_nomination_path(status:"createNom")  %>
            </div> 
        <% end %>
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
        <div class="table-responsive">
            <table class="table table-bordered gridTable" id="nominations">
            <thead class="gridheader">
              <tr>
                <th>Ref#</th>
                <% if ($userRole_frm == "Transporter")  %>
                  <th>Supplier Name</th>
                <% end %>
                <th>Start Date</th>
                <th>Cessation Date</th>
                <th>Injection Details</th>
                <th>Offtake Details</th>
                <th>Nomination Type</th>
                <th>Status</th>
                <% if ($userRole_frm == "Supplier")  %>
                  <th>Action</th>
                <% end %>
                
              </tr>
            </thead>
            <tbody>                          
                 <% @nominations.each do |key,value| %>
                    <% value.each do |keyNomination,valueNomination| %>   
                        <% valueNomination.each do |val| %>
                            <tr>
                              <td><%= val["nominationid"] %></td>
                                <% if ($userRole_frm == "Transporter")  %>
                                <td><%= val["fname"] %></td>
                                <% end %>
                                <td><%= val["startdate_and_time"] %></td>
                                <td><%= val["enddate_and_time"] %></td>
                                <td><%= val["injection_point"] %> - <%= val["injection_quantity"] %></td>
                                <td><%= val["offtake_point"] %> - <%= val["offtake_quantity"] %></td>
                                <td><%= val["nomination_type"] %></td>
                                <td><%= val["status"] %></td>
                                <% if ($userRole_frm == "Supplier")  %>
                                    <td class="text-center">     
                                        <%= link_to "<span class='glyphicon glyphicon-edit'></span>".html_safe, new_nomination_path(status:"modifyNom",capacity_ref:val["capacity_ref"],
                                         fname:val["fname"],startdate_and_time:val["startdate_and_time"],
                                         enddate_and_time:val["enddate_and_time"],injection_point:val["injection_point"],
                                         injection_quantity:val["injection_quantity"],offtake_point:val["offtake_point"],
                                         offtake_quantity:val["offtake_quantity"],nomination_type:val["nomination_type"],
                                        statusNomination:val["status"],nominationid:val["nominationid"])   %>
                                     </td>
                                <% end %>
                            </tr>                                                                     
                    <% end %>   
                <% end %>
                <% end %>
            </tbody>
          </table>
        </div>
    </div>  
        </div>
      </div>
</div>
<footer>
  <p></p>
  <p></p>
</footer>

app/views/nominations/new.html.erb
<%= render "layouts/header"  %>

<div class="container-fluid white-container nopad">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <%= render "layouts/sidenav"  %>       
        </div>
        <div class="col-sm-9 col-md-11">        
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
            <div class="pull-left"> 
                <% if @status == "createNom" %>
                    <h3 class="pageheading">Create Nomination</h3>
                 <% elsif @status == "modifyNom" %>
                    <h3 class="pageheading">Modify Nomination</h3>
                 <% else %>
                    <h3 class="pageheading">Nomination Details</h3>
                 <% end %>                
            </div>
            <div class="pull-right">
                <% if @status == "createNom" or @status == "modifyNom" %>
                    <%= link_to "<button class='btn btn-primary btn-small'>Back</button>".html_safe, nominations_path %>
                 <% else %>
                     <%= link_to '/nominations/notification' do %>
                        <span class='btn btn-primary btn-small'>Back</span>
                    <% end %>
                 <% end %> 
            </div>        
        </div> 
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
       <%= bootstrap_form_for @nomination, url: {action: "create"} do |f| %>
            <% if @status == "modifyNom" or @status == "viewNom" %>
            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 nopadmar">   
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">                   
                    <%= f.text_field :capacity, value: @nominationid, label:"Ref#", disabled: true %>
                </div>
            </div>
            <% end %>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"> 
                <% if @status == "viewNom" %>
                    <%= f.date_field :nominationstartdate, value: "Nomination Start Date", label:"Nomination Start Date", disabled: true %>
                <% elsif @status == "modifyNom" %>
                    <%= f.date_field :nominationstartdate, value: @startdate_and_time, label:"Nomination Start Date" %>
                    <%= f.hidden_field :hiddenNominationId, value: @nominationid %>
                <% else %>
                    <%= f.date_field :nominationstartdate, label:"Nomination Start Date", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                     <%= f.date_field :nominationenddate, label: "Cessation Date", disabled: true %>
                <% elsif @status == "modifyNom" %>
                     <%= f.date_field :nominationenddate, label: "Cessation Date", value: @enddate_and_time %>
                <% else %>
                    <%= f.date_field :nominationenddate, label: "Cessation Date", required: true %>
                <% end %>                    
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :injectionpoint, value: "Injection Point" , label: "Injection Point", disabled: true %>
                <% elsif @status == "modifyNom" %>
                    <%= f.text_field :injectionpoint, value: @injection_point, label: "Injection Point" %>
                <% else %>
                    <%= f.text_field :injectionpoint, label: "Injection Point", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :injectionquantity, value: "Injection Quantity" ,label: "Injection Quantity", disabled: true %>
                <% elsif @status == "modifyNom" %>
                    <%= f.text_field :injectionquantity, value: @injection_quantity ,label: "Injection Quantity" %>
                <% else %>
                    <%= f.text_field :injectionquantity, label: "Injection Quantity", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                    <%= f.text_field :offtakepoint, Value: "Offtake Point", label: "Offtake Point", disabled: true %>
                 <% elsif @status == "modifyNom" %>
                    <%= f.text_field :offtakepoint, Value: @offtake_point, label: "Offtake Point" %>
                <% else %>
                    <%= f.text_field :offtakepoint, label: "Offtake Point", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">  
                <% if @status == "viewNom" %>
                    <%= f.text_field :offtakequantity, Value: "Offtake Quantity",label: "Offtake Quantity", disabled: true %>
                 <% elsif @status == "modifyNom" %>
                    <%= f.text_field :offtakequantity, Value: @offtake_quantity,label: "Offtake Quantity" %>
                <% else %>
                    <%= f.text_field :offtakequantity, label: "Offtake Quantity", required: true %>
                <% end %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   
                <% if @status == "viewNom" %>
                    <%= f.text_field :capacity, value: "Ref#", label:"Capacity Right", disabled: true %>
                <% elsif @status == "modifyNom" %>
                    <%= f.text_field :capacity, value: @capacityRef, label:"Capacity Right" %>
                <% else %>
                    <%= f.text_field :capacity, label: "Ref#", required: true %>
                <% end %>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                
                <% if @status == "modifyNom" %>
                    <%= f.submit "Renominate", class: "btn btn-primary btn-top-spacing align-center" %>
                    <%= f.hidden_field :hiddenStatus, value: "Modify" %>
                <% end %>
                <% if @status == "createNom" %>
                    <%= f.submit "Submit", class: "btn btn-primary btn-top-spacing align-center" %>
                    <%= f.hidden_field :hiddenStatus, value: "Create" %>
                <% end %>               
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 btn-top-spacing">  
                 <% if @status == "viewNom" or @status == "modifyNom" %>
                    <span class = "label label-warning label-nomination">Initial Nomination</span> <span class = "label label-success label-nomination">Accepted</span>    
                <% end %>   
            </div>
        <% end %>
    </div>  
        </div>
      </div>
</div>
<footer>
  <p></p>
  <p></p>
</footer>

app/views/nominations/notification.html.erb
<%= render "layouts/header"  %>

<div class="container-fluid white-container nopad">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <%= render "layouts/sidenav"  %>       
        </div>
        <div class="col-sm-9 col-md-11">  
            <% if ($userRole_frm == "Transporter")  %>  
                <div class="alert alert-danger btn-top-spacing">Transporters don't have permission to access this page</div>
            <% else %>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
        <div class="pull-left"> <h3 class="pageheading">Notifications</h3></div>
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
        <div class="table-responsive">
            <table class="table table-bordered gridTable" id="notification">
            <thead class="gridheader">
                <tr>
                <th>Notification#</th>
                <th>Details</th>
                <th>Action</th>             
             </tr>
            </thead>
            <tbody>                          
                 <% @notifications.each do |key,value| %>
                    <% value.each do |val| %>                                    
                            <tr>                              
                                <td><%= val["notificationNo"] %></td>
                                <td><%= val["Details"] %></td>
                                <td class="text-center">
                                    <%= link_to "<span class='glyphicon glyphicon-eye-open'></span>".html_safe, new_nomination_path(status:"viewNom")  %>
                                </td>
                            </tr>                                                                     
                    <% end %>                              
                <% end %>
            </tbody>
          </table>
        </div>
    </div>  
            <%end %>
        </div>
      </div>
</div>
<footer>
  <p></p>
  <p></p>
</footer>

app/views/nominations/schedule.html.erb
<%= render "layouts/header"  %>

<div class="container-fluid white-container nopad">
      <div class="row">
        <div class="col-sm-3 col-md-1 sidebar">
            <%= render "layouts/sidenav"  %>       
        </div>
        <div class="col-sm-9 col-md-11">  
            <% if ($userRole_frm == "Supplier")  %>  
                <div class="alert alert-danger btn-top-spacing">Suppliers don't have permission to access this page</div>
            <% else %>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 contentheader"> 
        <div class="pull-left"> <h3 class="pageheading">Schedule</h3></div>
    </div>
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadmar">                   
        <div class="table-responsive">
            <table class="table table-bordered gridTable" id="schedule">
            <thead class="gridheader">
               <tr>
                <th>Date and Time</th>
                <th>Injection Point</th>
                <th>Injection Quantity</th>   
                <th>Offtake Point</th>  
                <th>Offtake Quantity</th>
             </tr>
            </thead>
            <tbody>                          
                <% @schedules.each do |key,value| %>
                    <% value.each do |keySchedule,valSchedule| %> 
                    <% valSchedule.each do |val| %>
                            <tr>                              
                                <td><%= val["date_and_time"] %></td>
                                <td><%= val["injection_point"] %></td>
                                <td><%= val["injection_quantity"] %></td>
                                <td><%= val["offtake_point"] %></td>
                                <td><%= val["offtake_quantity"] %></td>
                            </tr>                                                                     
                    <% end %>                              
                <% end %>
            <% end %> 
            </tbody>
          </table>
        </div>
    </div>  
            <%end %>
        </div>
      </div>
</div>
<footer>
  <p></p>
  <p></p>
</footer>

app/views/shipper_login/index.html.erb
<div class="container-fluid">
    <div class="container">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center loginTopSpace">
                   <%=image_tag("shipper_icon.png")%>
                </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12 loginwrap">
                    <h1>Welcome Shipper!</h1>
                   <%= bootstrap_form_for @slogin, url: {action: "create"} do |f| %>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.text_field :username, hide_label: true, placeholder: "Username", control_class: "logininput", required: true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.password_field :password, hide_label: true, placeholder: "Password", control_class: "pwdinput", required:true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.hidden_field :hiddenType, value: "Supplier" %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.submit "Login", class: "login-btn align-center" %>
                        </div>
                    <% end %>
                </div>
               </div>            
        </div>
    </div>
</div>

app/views/transporter_login/index.html.erb
<div class="container-fluid">
    <div class="container">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center loginTopSpace">
                   <%=image_tag("transporter_icon.png")%>
                </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12 loginwrap">
                    <h1>Welcome Transporter!</h1>
                   <%= bootstrap_form_for @tlogin, url: {action: "create"} do |f| %>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.text_field :username, hide_label: true, placeholder: "Username", control_class: "logininput", required: true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.password_field :password, hide_label: true, placeholder: "Password", control_class: "pwdinput", required:true %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.hidden_field :hiddenType, value: "Transporter" %>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">                   
                            <%= f.submit "Login", class: "login-btn align-center" %>
                        </div>
                    <% end %>
                </div>
               </div>            
        </div>
    </div>
</div>